### ISSUE TITLE
Missing sources for docker-socat , mailmock and swagger-ui

### ISSUE THREAD

**Issue by olljanat** [mistcommunity/mist-ce#14]
`docker-compose.yml` seems to contain these image references:
```yaml
image: mist/docker-socat
image: mist/mailmock
image: mist/swagger-ui
```

And looks that source codes of those does not exist in https://github.com/mistio

It might be that those are just binary sharing for images coming from else where but it needs to be investigated.
